sudo: required
services:
  - docker
before_install:
  - docker build -t wojtazik/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true wojtazik/react-test npm test

after_success:
  - docker build -t wojtazik/multi-client ./client
  - docker build -t wojtazik/multi-nginx ./nginx
  - docker build -t wojtazik/multi-server ./server
  - docker build -t wojtazik/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push wojtazik/multi-client
  - docker push wojtazik/multi-nginx
  - docker push wojtazik/multi-server
  - docker push wojtazik/multi-worker
deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-721189591237
  bucket_path: docker-complex
  on:
    branch: master
  access_key_id : $AWS_ACCESS_KEY
  secret_access_key : $AWS_SECRET_KEY